// Code generated by counterfeiter. DO NOT EDIT.
package directorfakes

import (
	"sync"

	directora "github.com/cloudfoundry/bosh-cli/v7/director"
	"github.com/cloudfoundry/bosh-utils/logger"
	"github.com/rkoster/instant-bosh/internal/director"
)

type FakeDirectorFactory struct {
	NewDirectorStub        func(*director.Config, logger.Logger) (directora.Director, error)
	newDirectorMutex       sync.RWMutex
	newDirectorArgsForCall []struct {
		arg1 *director.Config
		arg2 logger.Logger
	}
	newDirectorReturns struct {
		result1 directora.Director
		result2 error
	}
	newDirectorReturnsOnCall map[int]struct {
		result1 directora.Director
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDirectorFactory) NewDirector(arg1 *director.Config, arg2 logger.Logger) (directora.Director, error) {
	fake.newDirectorMutex.Lock()
	ret, specificReturn := fake.newDirectorReturnsOnCall[len(fake.newDirectorArgsForCall)]
	fake.newDirectorArgsForCall = append(fake.newDirectorArgsForCall, struct {
		arg1 *director.Config
		arg2 logger.Logger
	}{arg1, arg2})
	stub := fake.NewDirectorStub
	fakeReturns := fake.newDirectorReturns
	fake.recordInvocation("NewDirector", []interface{}{arg1, arg2})
	fake.newDirectorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDirectorFactory) NewDirectorCallCount() int {
	fake.newDirectorMutex.RLock()
	defer fake.newDirectorMutex.RUnlock()
	return len(fake.newDirectorArgsForCall)
}

func (fake *FakeDirectorFactory) NewDirectorCalls(stub func(*director.Config, logger.Logger) (directora.Director, error)) {
	fake.newDirectorMutex.Lock()
	defer fake.newDirectorMutex.Unlock()
	fake.NewDirectorStub = stub
}

func (fake *FakeDirectorFactory) NewDirectorArgsForCall(i int) (*director.Config, logger.Logger) {
	fake.newDirectorMutex.RLock()
	defer fake.newDirectorMutex.RUnlock()
	argsForCall := fake.newDirectorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDirectorFactory) NewDirectorReturns(result1 directora.Director, result2 error) {
	fake.newDirectorMutex.Lock()
	defer fake.newDirectorMutex.Unlock()
	fake.NewDirectorStub = nil
	fake.newDirectorReturns = struct {
		result1 directora.Director
		result2 error
	}{result1, result2}
}

func (fake *FakeDirectorFactory) NewDirectorReturnsOnCall(i int, result1 directora.Director, result2 error) {
	fake.newDirectorMutex.Lock()
	defer fake.newDirectorMutex.Unlock()
	fake.NewDirectorStub = nil
	if fake.newDirectorReturnsOnCall == nil {
		fake.newDirectorReturnsOnCall = make(map[int]struct {
			result1 directora.Director
			result2 error
		})
	}
	fake.newDirectorReturnsOnCall[i] = struct {
		result1 directora.Director
		result2 error
	}{result1, result2}
}

func (fake *FakeDirectorFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDirectorFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ director.DirectorFactory = new(FakeDirectorFactory)
