// Code generated by counterfeiter. DO NOT EDIT.
package directorfakes

import (
	"context"
	"sync"

	"github.com/rkoster/instant-bosh/internal/director"
	"github.com/rkoster/instant-bosh/internal/docker"
)

type FakeConfigProvider struct {
	GetDirectorConfigStub        func(context.Context, *docker.Client) (*director.Config, error)
	getDirectorConfigMutex       sync.RWMutex
	getDirectorConfigArgsForCall []struct {
		arg1 context.Context
		arg2 *docker.Client
	}
	getDirectorConfigReturns struct {
		result1 *director.Config
		result2 error
	}
	getDirectorConfigReturnsOnCall map[int]struct {
		result1 *director.Config
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigProvider) GetDirectorConfig(arg1 context.Context, arg2 *docker.Client) (*director.Config, error) {
	fake.getDirectorConfigMutex.Lock()
	ret, specificReturn := fake.getDirectorConfigReturnsOnCall[len(fake.getDirectorConfigArgsForCall)]
	fake.getDirectorConfigArgsForCall = append(fake.getDirectorConfigArgsForCall, struct {
		arg1 context.Context
		arg2 *docker.Client
	}{arg1, arg2})
	stub := fake.GetDirectorConfigStub
	fakeReturns := fake.getDirectorConfigReturns
	fake.recordInvocation("GetDirectorConfig", []interface{}{arg1, arg2})
	fake.getDirectorConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConfigProvider) GetDirectorConfigCallCount() int {
	fake.getDirectorConfigMutex.RLock()
	defer fake.getDirectorConfigMutex.RUnlock()
	return len(fake.getDirectorConfigArgsForCall)
}

func (fake *FakeConfigProvider) GetDirectorConfigCalls(stub func(context.Context, *docker.Client) (*director.Config, error)) {
	fake.getDirectorConfigMutex.Lock()
	defer fake.getDirectorConfigMutex.Unlock()
	fake.GetDirectorConfigStub = stub
}

func (fake *FakeConfigProvider) GetDirectorConfigArgsForCall(i int) (context.Context, *docker.Client) {
	fake.getDirectorConfigMutex.RLock()
	defer fake.getDirectorConfigMutex.RUnlock()
	argsForCall := fake.getDirectorConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeConfigProvider) GetDirectorConfigReturns(result1 *director.Config, result2 error) {
	fake.getDirectorConfigMutex.Lock()
	defer fake.getDirectorConfigMutex.Unlock()
	fake.GetDirectorConfigStub = nil
	fake.getDirectorConfigReturns = struct {
		result1 *director.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigProvider) GetDirectorConfigReturnsOnCall(i int, result1 *director.Config, result2 error) {
	fake.getDirectorConfigMutex.Lock()
	defer fake.getDirectorConfigMutex.Unlock()
	fake.GetDirectorConfigStub = nil
	if fake.getDirectorConfigReturnsOnCall == nil {
		fake.getDirectorConfigReturnsOnCall = make(map[int]struct {
			result1 *director.Config
			result2 error
		})
	}
	fake.getDirectorConfigReturnsOnCall[i] = struct {
		result1 *director.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ director.ConfigProvider = new(FakeConfigProvider)
