// Code generated by counterfeiter. DO NOT EDIT.
package containerfakes

import (
	"context"
	"sync"

	"github.com/rkoster/instant-bosh/internal/container"
)

type FakeClient struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ExecCommandStub        func(context.Context, string, []string) (string, error)
	execCommandMutex       sync.RWMutex
	execCommandArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	execCommandReturns struct {
		result1 string
		result2 error
	}
	execCommandReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetHostAddressStub        func() string
	getHostAddressMutex       sync.RWMutex
	getHostAddressArgsForCall []struct {
	}
	getHostAddressReturns struct {
		result1 string
	}
	getHostAddressReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeClient) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeClient) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) ExecCommand(arg1 context.Context, arg2 string, arg3 []string) (string, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.execCommandMutex.Lock()
	ret, specificReturn := fake.execCommandReturnsOnCall[len(fake.execCommandArgsForCall)]
	fake.execCommandArgsForCall = append(fake.execCommandArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.ExecCommandStub
	fakeReturns := fake.execCommandReturns
	fake.recordInvocation("ExecCommand", []interface{}{arg1, arg2, arg3Copy})
	fake.execCommandMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ExecCommandCallCount() int {
	fake.execCommandMutex.RLock()
	defer fake.execCommandMutex.RUnlock()
	return len(fake.execCommandArgsForCall)
}

func (fake *FakeClient) ExecCommandCalls(stub func(context.Context, string, []string) (string, error)) {
	fake.execCommandMutex.Lock()
	defer fake.execCommandMutex.Unlock()
	fake.ExecCommandStub = stub
}

func (fake *FakeClient) ExecCommandArgsForCall(i int) (context.Context, string, []string) {
	fake.execCommandMutex.RLock()
	defer fake.execCommandMutex.RUnlock()
	argsForCall := fake.execCommandArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) ExecCommandReturns(result1 string, result2 error) {
	fake.execCommandMutex.Lock()
	defer fake.execCommandMutex.Unlock()
	fake.ExecCommandStub = nil
	fake.execCommandReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ExecCommandReturnsOnCall(i int, result1 string, result2 error) {
	fake.execCommandMutex.Lock()
	defer fake.execCommandMutex.Unlock()
	fake.ExecCommandStub = nil
	if fake.execCommandReturnsOnCall == nil {
		fake.execCommandReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.execCommandReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetHostAddress() string {
	fake.getHostAddressMutex.Lock()
	ret, specificReturn := fake.getHostAddressReturnsOnCall[len(fake.getHostAddressArgsForCall)]
	fake.getHostAddressArgsForCall = append(fake.getHostAddressArgsForCall, struct {
	}{})
	stub := fake.GetHostAddressStub
	fakeReturns := fake.getHostAddressReturns
	fake.recordInvocation("GetHostAddress", []interface{}{})
	fake.getHostAddressMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) GetHostAddressCallCount() int {
	fake.getHostAddressMutex.RLock()
	defer fake.getHostAddressMutex.RUnlock()
	return len(fake.getHostAddressArgsForCall)
}

func (fake *FakeClient) GetHostAddressCalls(stub func() string) {
	fake.getHostAddressMutex.Lock()
	defer fake.getHostAddressMutex.Unlock()
	fake.GetHostAddressStub = stub
}

func (fake *FakeClient) GetHostAddressReturns(result1 string) {
	fake.getHostAddressMutex.Lock()
	defer fake.getHostAddressMutex.Unlock()
	fake.GetHostAddressStub = nil
	fake.getHostAddressReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) GetHostAddressReturnsOnCall(i int, result1 string) {
	fake.getHostAddressMutex.Lock()
	defer fake.getHostAddressMutex.Unlock()
	fake.GetHostAddressStub = nil
	if fake.getHostAddressReturnsOnCall == nil {
		fake.getHostAddressReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getHostAddressReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ container.Client = new(FakeClient)
