// Code generated by counterfeiter. DO NOT EDIT.
package registryfakes

import (
	"context"
	"sync"

	"github.com/rkoster/instant-bosh/internal/registry"
)

type FakeClient struct {
	ExtractFileFromImageStub        func(context.Context, string, string) ([]byte, error)
	extractFileFromImageMutex       sync.RWMutex
	extractFileFromImageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	extractFileFromImageReturns struct {
		result1 []byte
		result2 error
	}
	extractFileFromImageReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	FindTagsForDigestStub        func(context.Context, string, string) ([]string, error)
	findTagsForDigestMutex       sync.RWMutex
	findTagsForDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findTagsForDigestReturns struct {
		result1 []string
		result2 error
	}
	findTagsForDigestReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetImageDigestStub        func(context.Context, string) (string, error)
	getImageDigestMutex       sync.RWMutex
	getImageDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getImageDigestReturns struct {
		result1 string
		result2 error
	}
	getImageDigestReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetManifestDiffStub        func(context.Context, registry.ImageInfo, registry.ImageInfo) (string, error)
	getManifestDiffMutex       sync.RWMutex
	getManifestDiffArgsForCall []struct {
		arg1 context.Context
		arg2 registry.ImageInfo
		arg3 registry.ImageInfo
	}
	getManifestDiffReturns struct {
		result1 string
		result2 error
	}
	getManifestDiffReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ResolveImageRefStub        func(context.Context, string) (string, string, error)
	resolveImageRefMutex       sync.RWMutex
	resolveImageRefArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	resolveImageRefReturns struct {
		result1 string
		result2 string
		result3 error
	}
	resolveImageRefReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) ExtractFileFromImage(arg1 context.Context, arg2 string, arg3 string) ([]byte, error) {
	fake.extractFileFromImageMutex.Lock()
	ret, specificReturn := fake.extractFileFromImageReturnsOnCall[len(fake.extractFileFromImageArgsForCall)]
	fake.extractFileFromImageArgsForCall = append(fake.extractFileFromImageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ExtractFileFromImageStub
	fakeReturns := fake.extractFileFromImageReturns
	fake.recordInvocation("ExtractFileFromImage", []interface{}{arg1, arg2, arg3})
	fake.extractFileFromImageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ExtractFileFromImageCallCount() int {
	fake.extractFileFromImageMutex.RLock()
	defer fake.extractFileFromImageMutex.RUnlock()
	return len(fake.extractFileFromImageArgsForCall)
}

func (fake *FakeClient) ExtractFileFromImageCalls(stub func(context.Context, string, string) ([]byte, error)) {
	fake.extractFileFromImageMutex.Lock()
	defer fake.extractFileFromImageMutex.Unlock()
	fake.ExtractFileFromImageStub = stub
}

func (fake *FakeClient) ExtractFileFromImageArgsForCall(i int) (context.Context, string, string) {
	fake.extractFileFromImageMutex.RLock()
	defer fake.extractFileFromImageMutex.RUnlock()
	argsForCall := fake.extractFileFromImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) ExtractFileFromImageReturns(result1 []byte, result2 error) {
	fake.extractFileFromImageMutex.Lock()
	defer fake.extractFileFromImageMutex.Unlock()
	fake.ExtractFileFromImageStub = nil
	fake.extractFileFromImageReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ExtractFileFromImageReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.extractFileFromImageMutex.Lock()
	defer fake.extractFileFromImageMutex.Unlock()
	fake.ExtractFileFromImageStub = nil
	if fake.extractFileFromImageReturnsOnCall == nil {
		fake.extractFileFromImageReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.extractFileFromImageReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) FindTagsForDigest(arg1 context.Context, arg2 string, arg3 string) ([]string, error) {
	fake.findTagsForDigestMutex.Lock()
	ret, specificReturn := fake.findTagsForDigestReturnsOnCall[len(fake.findTagsForDigestArgsForCall)]
	fake.findTagsForDigestArgsForCall = append(fake.findTagsForDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindTagsForDigestStub
	fakeReturns := fake.findTagsForDigestReturns
	fake.recordInvocation("FindTagsForDigest", []interface{}{arg1, arg2, arg3})
	fake.findTagsForDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) FindTagsForDigestCallCount() int {
	fake.findTagsForDigestMutex.RLock()
	defer fake.findTagsForDigestMutex.RUnlock()
	return len(fake.findTagsForDigestArgsForCall)
}

func (fake *FakeClient) FindTagsForDigestCalls(stub func(context.Context, string, string) ([]string, error)) {
	fake.findTagsForDigestMutex.Lock()
	defer fake.findTagsForDigestMutex.Unlock()
	fake.FindTagsForDigestStub = stub
}

func (fake *FakeClient) FindTagsForDigestArgsForCall(i int) (context.Context, string, string) {
	fake.findTagsForDigestMutex.RLock()
	defer fake.findTagsForDigestMutex.RUnlock()
	argsForCall := fake.findTagsForDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) FindTagsForDigestReturns(result1 []string, result2 error) {
	fake.findTagsForDigestMutex.Lock()
	defer fake.findTagsForDigestMutex.Unlock()
	fake.FindTagsForDigestStub = nil
	fake.findTagsForDigestReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) FindTagsForDigestReturnsOnCall(i int, result1 []string, result2 error) {
	fake.findTagsForDigestMutex.Lock()
	defer fake.findTagsForDigestMutex.Unlock()
	fake.FindTagsForDigestStub = nil
	if fake.findTagsForDigestReturnsOnCall == nil {
		fake.findTagsForDigestReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.findTagsForDigestReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetImageDigest(arg1 context.Context, arg2 string) (string, error) {
	fake.getImageDigestMutex.Lock()
	ret, specificReturn := fake.getImageDigestReturnsOnCall[len(fake.getImageDigestArgsForCall)]
	fake.getImageDigestArgsForCall = append(fake.getImageDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetImageDigestStub
	fakeReturns := fake.getImageDigestReturns
	fake.recordInvocation("GetImageDigest", []interface{}{arg1, arg2})
	fake.getImageDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetImageDigestCallCount() int {
	fake.getImageDigestMutex.RLock()
	defer fake.getImageDigestMutex.RUnlock()
	return len(fake.getImageDigestArgsForCall)
}

func (fake *FakeClient) GetImageDigestCalls(stub func(context.Context, string) (string, error)) {
	fake.getImageDigestMutex.Lock()
	defer fake.getImageDigestMutex.Unlock()
	fake.GetImageDigestStub = stub
}

func (fake *FakeClient) GetImageDigestArgsForCall(i int) (context.Context, string) {
	fake.getImageDigestMutex.RLock()
	defer fake.getImageDigestMutex.RUnlock()
	argsForCall := fake.getImageDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) GetImageDigestReturns(result1 string, result2 error) {
	fake.getImageDigestMutex.Lock()
	defer fake.getImageDigestMutex.Unlock()
	fake.GetImageDigestStub = nil
	fake.getImageDigestReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetImageDigestReturnsOnCall(i int, result1 string, result2 error) {
	fake.getImageDigestMutex.Lock()
	defer fake.getImageDigestMutex.Unlock()
	fake.GetImageDigestStub = nil
	if fake.getImageDigestReturnsOnCall == nil {
		fake.getImageDigestReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getImageDigestReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetManifestDiff(arg1 context.Context, arg2 registry.ImageInfo, arg3 registry.ImageInfo) (string, error) {
	fake.getManifestDiffMutex.Lock()
	ret, specificReturn := fake.getManifestDiffReturnsOnCall[len(fake.getManifestDiffArgsForCall)]
	fake.getManifestDiffArgsForCall = append(fake.getManifestDiffArgsForCall, struct {
		arg1 context.Context
		arg2 registry.ImageInfo
		arg3 registry.ImageInfo
	}{arg1, arg2, arg3})
	stub := fake.GetManifestDiffStub
	fakeReturns := fake.getManifestDiffReturns
	fake.recordInvocation("GetManifestDiff", []interface{}{arg1, arg2, arg3})
	fake.getManifestDiffMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetManifestDiffCallCount() int {
	fake.getManifestDiffMutex.RLock()
	defer fake.getManifestDiffMutex.RUnlock()
	return len(fake.getManifestDiffArgsForCall)
}

func (fake *FakeClient) GetManifestDiffCalls(stub func(context.Context, registry.ImageInfo, registry.ImageInfo) (string, error)) {
	fake.getManifestDiffMutex.Lock()
	defer fake.getManifestDiffMutex.Unlock()
	fake.GetManifestDiffStub = stub
}

func (fake *FakeClient) GetManifestDiffArgsForCall(i int) (context.Context, registry.ImageInfo, registry.ImageInfo) {
	fake.getManifestDiffMutex.RLock()
	defer fake.getManifestDiffMutex.RUnlock()
	argsForCall := fake.getManifestDiffArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) GetManifestDiffReturns(result1 string, result2 error) {
	fake.getManifestDiffMutex.Lock()
	defer fake.getManifestDiffMutex.Unlock()
	fake.GetManifestDiffStub = nil
	fake.getManifestDiffReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetManifestDiffReturnsOnCall(i int, result1 string, result2 error) {
	fake.getManifestDiffMutex.Lock()
	defer fake.getManifestDiffMutex.Unlock()
	fake.GetManifestDiffStub = nil
	if fake.getManifestDiffReturnsOnCall == nil {
		fake.getManifestDiffReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getManifestDiffReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ResolveImageRef(arg1 context.Context, arg2 string) (string, string, error) {
	fake.resolveImageRefMutex.Lock()
	ret, specificReturn := fake.resolveImageRefReturnsOnCall[len(fake.resolveImageRefArgsForCall)]
	fake.resolveImageRefArgsForCall = append(fake.resolveImageRefArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ResolveImageRefStub
	fakeReturns := fake.resolveImageRefReturns
	fake.recordInvocation("ResolveImageRef", []interface{}{arg1, arg2})
	fake.resolveImageRefMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeClient) ResolveImageRefCallCount() int {
	fake.resolveImageRefMutex.RLock()
	defer fake.resolveImageRefMutex.RUnlock()
	return len(fake.resolveImageRefArgsForCall)
}

func (fake *FakeClient) ResolveImageRefCalls(stub func(context.Context, string) (string, string, error)) {
	fake.resolveImageRefMutex.Lock()
	defer fake.resolveImageRefMutex.Unlock()
	fake.ResolveImageRefStub = stub
}

func (fake *FakeClient) ResolveImageRefArgsForCall(i int) (context.Context, string) {
	fake.resolveImageRefMutex.RLock()
	defer fake.resolveImageRefMutex.RUnlock()
	argsForCall := fake.resolveImageRefArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) ResolveImageRefReturns(result1 string, result2 string, result3 error) {
	fake.resolveImageRefMutex.Lock()
	defer fake.resolveImageRefMutex.Unlock()
	fake.ResolveImageRefStub = nil
	fake.resolveImageRefReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) ResolveImageRefReturnsOnCall(i int, result1 string, result2 string, result3 error) {
	fake.resolveImageRefMutex.Lock()
	defer fake.resolveImageRefMutex.Unlock()
	fake.ResolveImageRefStub = nil
	if fake.resolveImageRefReturnsOnCall == nil {
		fake.resolveImageRefReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 error
		})
	}
	fake.resolveImageRefReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ registry.Client = new(FakeClient)
